/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2006, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.ws.types;


public class ElemAttribRef {
    protected java.lang.String country;
    protected org.jboss.ws.types.Employee USEmployee;
    protected org.jboss.ws.types.Address USAddress;

    public ElemAttribRef() {
    }

    public ElemAttribRef(java.lang.String country, org.jboss.ws.types.Employee USEmployee, org.jboss.ws.types.Address USAddress) {
        this.country = country;
        this.USEmployee = USEmployee;
        this.USAddress = USAddress;
    }

    public java.lang.String getCountry() {
        return country;
    }

    public void setCountry(java.lang.String country) {
        this.country = country;
    }

    public org.jboss.ws.types.Employee getUSEmployee() {
        return USEmployee;
    }

    public void setUSEmployee(org.jboss.ws.types.Employee USEmployee) {
        this.USEmployee = USEmployee;
    }

    public org.jboss.ws.types.Address getUSAddress() {
        return USAddress;
    }

    public void setUSAddress(org.jboss.ws.types.Address USAddress) {
        this.USAddress = USAddress;
    }
}
