/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2006, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
//Auto Generated by jbossws - Please do not edit!!!

package org.jboss.test.ws.jaxrpc.jbws643;

public class KeywordType
{

   protected java.lang.String raw;

   protected java.lang.String phrase;

   protected java.lang.String canonical;

   protected java.lang.String common;

   public KeywordType()
   {
   }

   public KeywordType(java.lang.String raw, java.lang.String phrase, java.lang.String canonical, java.lang.String common)
   {
      this.raw = raw;
      this.phrase = phrase;
      this.canonical = canonical;
      this.common = common;
   }

   public java.lang.String getRaw()
   {
      return raw;
   }

   public void setRaw(java.lang.String raw)
   {
      this.raw = raw;
   }

   public java.lang.String getPhrase()
   {
      return phrase;
   }

   public void setPhrase(java.lang.String phrase)
   {
      this.phrase = phrase;
   }

   public java.lang.String getCanonical()
   {
      return canonical;
   }

   public void setCanonical(java.lang.String canonical)
   {
      this.canonical = canonical;
   }

   public java.lang.String getCommon()
   {
      return common;
   }

   public void setCommon(java.lang.String common)
   {
      this.common = common;
   }

}
