<?xml version="1.0" encoding="UTF-8"?>
<definitions name='HelloServiceCtxRoot' targetNamespace='http://org.jboss.test.webservice/jbws165' xmlns='http://schemas.xmlsoap.org/wsdl/' xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/' xmlns:tns='http://org.jboss.test.webservice/jbws165' xmlns:xsd='http://www.w3.org/2001/XMLSchema'>
 <types/>
 <message name='Hello_hello'>
  <part name='String_1' type='xsd:string'/>
 </message>
 <message name='Hello_helloResponse'>
  <part name='result' type='xsd:string'/>
 </message>
 <portType name='Hello'>
  <operation name='hello' parameterOrder='String_1'>
   <input message='tns:Hello_hello'/>
   <output message='tns:Hello_helloResponse'/>
  </operation>
 </portType>
 <binding name='HelloBinding' type='tns:Hello'>
  <soap:binding style='rpc' transport='http://schemas.xmlsoap.org/soap/http'/>
  <operation name='hello'>
   <soap:operation soapAction=''/>
   <input>
    <soap:body namespace='http://org.jboss.test.webservice/jbws165' use='literal'/>
   </input>
   <output>
    <soap:body namespace='http://org.jboss.test.webservice/jbws165' use='literal'/>
   </output>
  </operation>
 </binding>
 <service name='HelloServiceCtxRoot'>
  <port binding='tns:HelloBinding' name='HelloPort'>
   <soap:address location='REPLACE_WITH_ACTUAL_URL'/>
  </port>
 </service>
</definitions>