/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2006, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jbws1184;


public class DataObject {
    protected java.lang.Boolean booleanValue;
    protected java.lang.Byte byteValue;
    protected java.lang.Float floatValue;
    protected java.lang.Integer integerValue;
    protected java.lang.Long longValue;
    protected java.lang.Short shortValue;
    
    public DataObject() {
    }
    
    public DataObject(java.lang.Boolean booleanValue, java.lang.Byte byteValue, java.lang.Float floatValue, java.lang.Integer integerValue, java.lang.Long longValue, java.lang.Short shortValue) {
        this.booleanValue = booleanValue;
        this.byteValue = byteValue;
        this.floatValue = floatValue;
        this.integerValue = integerValue;
        this.longValue = longValue;
        this.shortValue = shortValue;
    }
    
    public java.lang.Boolean getBooleanValue() {
        return booleanValue;
    }
    
    public void setBooleanValue(java.lang.Boolean booleanValue) {
        this.booleanValue = booleanValue;
    }
    
    public java.lang.Byte getByteValue() {
        return byteValue;
    }
    
    public void setByteValue(java.lang.Byte byteValue) {
        this.byteValue = byteValue;
    }
    
    public java.lang.Float getFloatValue() {
        return floatValue;
    }
    
    public void setFloatValue(java.lang.Float floatValue) {
        this.floatValue = floatValue;
    }
    
    public java.lang.Integer getIntegerValue() {
        return integerValue;
    }
    
    public void setIntegerValue(java.lang.Integer integerValue) {
        this.integerValue = integerValue;
    }
    
    public java.lang.Long getLongValue() {
        return longValue;
    }
    
    public void setLongValue(java.lang.Long longValue) {
        this.longValue = longValue;
    }
    
    public java.lang.Short getShortValue() {
        return shortValue;
    }
    
    public void setShortValue(java.lang.Short shortValue) {
        this.shortValue = shortValue;
    }
}
