/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2006, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
package org.jboss.test.ws.jaxrpc.marshall.types._arrays.javax.xml.namespace;


public class QNameArray {
    private javax.xml.namespace.QName[] value;
    
    public QNameArray() {
    }
    
    public QNameArray(javax.xml.namespace.QName[] sourceArray) {
        value = sourceArray;
    }
    
    public void fromArray(javax.xml.namespace.QName[] sourceArray) {
        this.value = sourceArray;
    }
    
    public javax.xml.namespace.QName[] toArray() {
        return value;
    }
    
    public javax.xml.namespace.QName[] getValue() {
        return value;
    }
    
    public void setValue(javax.xml.namespace.QName[] value) {
        this.value = value;
    }
}
