<?xml version="1.0" encoding="UTF-8"?>

<definitions name="ComplexTypesService"
	targetNamespace="http://org.jboss.ws" xmlns:tns="http://org.jboss.ws"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"> 
    
    <import namespace="http://org.jboss.ws"
		location="./Import.wsdl" />

	<service name="ComplexTypesService">
		<port name="ComplexTypesPort"
			binding="tns:ComplexTypesBinding">
			<soap:address location="REPLACE_WITH_ACTUAL_URL" />
		</port>
	</service>
</definitions>
