<?xml version="1.0" encoding="UTF-8"?>

<definitions name="TestService" targetNamespace="http://org.jboss.ws/jaxrpc"
	     xmlns:tns="http://org.jboss.ws/jaxrpc" 
	     xmlns="http://schemas.xmlsoap.org/wsdl/" 
	     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	     xmlns:ns2="http://org.jboss.ws/jaxrpc/types" 
	     xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	     xmlns:fab="http://www.fabrikam123.example.com/stock" 
	     xmlns:rmp="http://schemas.xmlsoap.org/ws/2005/02/rm/policy" 
	     xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy" 
	     xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
	     xmlns:foo1="http://foo.org/foo1"  
	     xmlns:foo2="http://foo.org/foo2"  
	     xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" >
  <wsp:Policy wsu:Id="RmPolicy" >
    <rmp:RMAssertion>
      <rmp:InactivityTimeout Milliseconds="600000" />
      <rmp:BaseRetransmissionInterval Milliseconds="3000" />
      <rmp:ExponentialBackoff />
      <rmp:AcknowledgementInterval Milliseconds="200" />
    </rmp:RMAssertion>
  </wsp:Policy>
  <wsp:Policy wsu:Id="uselessServicePolicy" >
    <fab:useless>nothing</fab:useless>
  </wsp:Policy>
  <wsp:Policy wsu:Id="uselessPortPolicy" >
    <fab:useless>nothing again</fab:useless>
  </wsp:Policy>
  <wsp:Policy wsu:Id="X509EndpointPolicy" >
    <sp:AsymmetricBinding>
      <wsp:Policy>
        <!-- Details omitted for readability -->
        <sp:IncludeTimestamp />
        <sp:OnlySignEntireHeadersAndBody />
      </wsp:Policy>
    </sp:AsymmetricBinding>
  </wsp:Policy>
  <wsp:Policy wsu:Id="SecureMessagePolicy" >
    <sp:SignedParts>
      <sp:Body />
    </sp:SignedParts>
    <sp:EncryptedParts>
      <sp:Body />
    </sp:EncryptedParts>
  </wsp:Policy>
  <types>
    <schema targetNamespace="http://org.jboss.ws/jaxrpc/types" xmlns:tns="http://org.jboss.ws/jaxrpc/types" xmlns:soap11-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://www.w3.org/2001/XMLSchema">
      <complexType name="echoSimpleUserType">
        <sequence>
          <element name="String_1" type="string" nillable="true"/>
          <element name="SimpleUserType_2" type="tns:SimpleUserType" nillable="true"/>
        </sequence>
      </complexType>
      <complexType name="SimpleUserType">
        <sequence>
          <element name="a" type="int"/>
          <element name="b" type="int"/>
        </sequence>
      </complexType>
      <complexType name="echoSimpleUserTypeResponse">
        <sequence>
          <element name="result" type="tns:SimpleUserType" nillable="true"/>
        </sequence>
      </complexType>
      <complexType name="echoString">
        <sequence>
          <element name="String_1" type="string" nillable="true"/>
          <element name="String_2" type="string" nillable="true"/>
        </sequence>
      </complexType>
      <complexType name="echoStringResponse">
        <sequence>
          <element name="result" type="string" nillable="true"/>
        </sequence>
      </complexType>
      <element name="echoSimpleUserType" type="tns:echoSimpleUserType"/>
      <element name="echoSimpleUserTypeResponse" type="tns:echoSimpleUserTypeResponse"/>
      <element name="echoString" type="tns:echoString"/>
      <element name="echoStringResponse" type="tns:echoStringResponse"/>
    </schema>
  </types>
  <message name="JaxRpcTestService_echoSimpleUserType">
    <part name="parameters" element="ns2:echoSimpleUserType"/>
  </message>
  <message name="JaxRpcTestService_echoSimpleUserTypeResponse">
    <part name="result" element="ns2:echoSimpleUserTypeResponse"/>
  </message>
  <message name="JaxRpcTestService_echoString">
    <part name="parameters" element="ns2:echoString"/>
  </message>
  <message name="JaxRpcTestService_echoStringResponse">
    <part name="result" element="ns2:echoStringResponse"/>
  </message>
  <portType name="JaxRpcTestService" wsp:PolicyURIs="#RmPolicy">
    <operation name="echoSimpleUserType">
      <input message="tns:JaxRpcTestService_echoSimpleUserType"/>
      <output message="tns:JaxRpcTestService_echoSimpleUserTypeResponse"/>
    </operation>
    <operation name="echoString">
      <input message="tns:JaxRpcTestService_echoString"/>
      <output message="tns:JaxRpcTestService_echoStringResponse"/>
    </operation>
  </portType>
  <binding name="JaxRpcTestServiceBinding" type="tns:JaxRpcTestService">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <wsp:PolicyReference URI="#RmPolicy" wsdl:required="true" />
    <wsp:PolicyReference URI="#X509EndpointPolicy" wsdl:required="true" />
	<foo1:bar wsdl:required="false"/>
    <foo2:bar/>
    <operation name="echoSimpleUserType">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
    <operation name="echoString">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="TestService">
    <wsp:PolicyReference URI="#uselessServicePolicy" wsdl:required="true" />
    <port name="JaxRpcTestServicePort" binding="tns:JaxRpcTestServiceBinding">
      <wsp:PolicyReference URI="#uselessPortPolicy" wsdl:required="true" />
      <foo1:bar wsdl:required="true"/>
      <soap:address location="REPLACE_WITH_ACTUAL_URL"/>
    </port>
  </service>
</definitions>
