/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2006, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package org.jboss.test.ws.jaxrpc.jbws720;

import javax.xml.soap.Name;
import javax.xml.soap.SOAPElement;

public class GetProperty
{
   protected String strAttr;
   protected String lang;
   protected String strElement;
   protected SOAPElement[] _any;

   public GetProperty()
   {
   }

   public GetProperty(String strAttr, String lang, String strElement, SOAPElement[] _any)
   {
      this.strAttr = strAttr;
      this.lang = lang;
      this.strElement = strElement;
      this._any = _any;
   }

   public String getStrAttr()
   {
      return strAttr;
   }

   public void setStrAttr(String strAttr)
   {
      this.strAttr = strAttr;
   }

   public String getLang()
   {
      return lang;
   }

   public void setLang(String lang)
   {
      this.lang = lang;
   }

   public String getStrElement()
   {
      return strElement;
   }

   public void setStrElement(String strElement)
   {
      this.strElement = strElement;
   }

   public SOAPElement[] get_any()
   {
      return _any;
   }

   public void set_any(SOAPElement[] _any)
   {
      this._any = _any;
   }
   
   public boolean equals(Object obj)
   {
      if ((obj instanceof GetProperty) == false) return false;
      return toString().equals(obj.toString());
   }
   
   public String toString() 
   {
      StringBuffer builder = null;
      if (_any != null && _any.length > 0)
      {
         builder = new StringBuffer();
         for (int i =0; i < _any.length; i++)
         {
            SOAPElement sel = _any[i];
            Name name = sel.getElementName();
            builder.append(name);
         }
      }
      return "[elmt=" + strElement + ",attr=" + strAttr + ",lang=" + lang + ",any=" + builder + "]";
   }
}
