/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2006, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.ws.types;


public class NillableType {
    protected java.lang.Byte myByte;
    protected byte myByte2;
    protected java.lang.Boolean myBool;
    protected boolean myBool2;
    protected java.lang.Short myShort;
    protected short myShort2;
    protected java.lang.Integer myInt;
    protected int myInt2;
    protected java.lang.Long myLong;
    protected long myLong2;
    protected java.lang.Float myFloat;
    protected float myFloat2;
    protected java.lang.Double myDouble;
    protected double myDouble2;

    public NillableType() {
    }

    public NillableType(java.lang.Byte myByte, byte myByte2, java.lang.Boolean myBool, boolean myBool2, java.lang.Short myShort, short myShort2, java.lang.Integer myInt, int myInt2, java.lang.Long myLong, long myLong2, java.lang.Float myFloat, float myFloat2, java.lang.Double myDouble, double myDouble2) {
        this.myByte = myByte;
        this.myByte2 = myByte2;
        this.myBool = myBool;
        this.myBool2 = myBool2;
        this.myShort = myShort;
        this.myShort2 = myShort2;
        this.myInt = myInt;
        this.myInt2 = myInt2;
        this.myLong = myLong;
        this.myLong2 = myLong2;
        this.myFloat = myFloat;
        this.myFloat2 = myFloat2;
        this.myDouble = myDouble;
        this.myDouble2 = myDouble2;
        }

    //These methods are not generated by wscompile - bug
    public java.lang.Byte getMyByte() { return myByte ;}

    public void setMyByte(java.lang.Byte myvar ){  myByte=myvar ;}

    public byte getMyByte2() { return myByte2 ;}

    public void setMyByte2(byte myvar ){  myByte2=myvar ;}
    //End

    public java.lang.Boolean getMyBool() { return myBool ;}

    public void setMyBool(java.lang.Boolean myBool) {
        this.myBool = myBool;
    }

    public boolean isMyBool2() {
        return myBool2;
    }

    public void setMyBool2(boolean myBool2) {
        this.myBool2 = myBool2;
    }

    public java.lang.Short getMyShort() {
        return myShort;
    }

    public void setMyShort(java.lang.Short myShort) {
        this.myShort = myShort;
    }

    public short getMyShort2() {
        return myShort2;
    }

    public void setMyShort2(short myShort2) {
        this.myShort2 = myShort2;
    }

    public java.lang.Integer getMyInt() {
        return myInt;
    }

    public void setMyInt(java.lang.Integer myInt) {
        this.myInt = myInt;
    }

    public int getMyInt2() {
        return myInt2;
    }

    public void setMyInt2(int myInt2) {
        this.myInt2 = myInt2;
    }

    public java.lang.Long getMyLong() {
        return myLong;
    }

    public void setMyLong(java.lang.Long myLong) {
        this.myLong = myLong;
    }

    public long getMyLong2() {
        return myLong2;
    }

    public void setMyLong2(long myLong2) {
        this.myLong2 = myLong2;
    }

    public java.lang.Float getMyFloat() {
        return myFloat;
    }

    public void setMyFloat(java.lang.Float myFloat) {
        this.myFloat = myFloat;
    }

    public float getMyFloat2() {
        return myFloat2;
    }

    public void setMyFloat2(float myFloat2) {
        this.myFloat2 = myFloat2;
    }

    public java.lang.Double getMyDouble() {
        return myDouble;
    }

    public void setMyDouble(java.lang.Double myDouble) {
        this.myDouble = myDouble;
    }

    public double getMyDouble2() {
        return myDouble2;
    }

    public void setMyDouble2(double myDouble2) {
        this.myDouble2 = myDouble2;
    }
}
