/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2006, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
//Auto Generated by jbossws - Please do not edit!!!
package org.jboss.test.ws.jaxrpc.marshall;

public class StandardTypes_shortTest_RequestStruct
{

   protected short short_1;

   public StandardTypes_shortTest_RequestStruct()
   {
   }

   public StandardTypes_shortTest_RequestStruct(short short_1)
   {
      this.short_1 = short_1;
   }

   public short getShort_1()
   {
      return short_1;
   }

   public void setShort_1(short short_1)
   {
      this.short_1 = short_1;
   }

}
