<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="urn:samples:ticket" xmlns:tns="urn:samples:ticket" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <message name="ticketMessage">
    <part name="ticketNo" type="xsd:int"/>
  </message>
  <message name="ticketRequest">
  </message>
  <portType name="TicketIssuer">
    <operation name="createTicket">
      <input message="tns:ticketRequest"/>
      <output message="tns:ticketMessage"/>
    </operation>
  </portType>
</definitions>