/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2006, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxrpc.encoded.marshalltest;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.rmi.Remote;
import java.rmi.RemoteException;
import java.util.Calendar;

public interface MarshallTest extends Remote
{
   public BigDecimal[] bigDecimalArrayTest(BigDecimal[] arrayOfBigDecimal_1) throws RemoteException;

   public BigDecimal[][] bigDecimalMultiArrayTest(BigDecimal[][] arrayOfarrayOfBigDecimal_1) throws RemoteException;

   public BigDecimal bigDecimalTest(BigDecimal bigDecimal_1) throws RemoteException;

   public BigInteger[] bigIntegerArrayTest(BigInteger[] arrayOfBigInteger_1) throws RemoteException;

   public BigInteger[][] bigIntegerMultiArrayTest(BigInteger[][] arrayOfarrayOfBigInteger_1) throws RemoteException;

   public BigInteger bigIntegerTest(BigInteger bigInteger_1) throws RemoteException;

   public boolean[] booleanArrayTest(boolean[] arrayOfboolean_1) throws RemoteException;

   public boolean[][] booleanMultiArrayTest(boolean[][] arrayOfarrayOfboolean_1) throws RemoteException;

   public boolean booleanTest(boolean boolean_1) throws RemoteException;

   public byte[] byteArrayTest(byte[] arrayOfbyte_1) throws RemoteException;

   public byte[][] byteMultiArrayTest(byte[][] arrayOfarrayOfbyte_1) throws RemoteException;

   public byte byteTest(byte byte_1) throws RemoteException;

   public Calendar[] calendarArrayTest(Calendar[] arrayOfCalendar_1) throws RemoteException;

   public Calendar[][] calendarMultiArrayTest(Calendar[][] arrayOfarrayOfCalendar_1) throws RemoteException;

   public Calendar calendarTest(Calendar calendar_1) throws RemoteException;

   public double[] doubleArrayTest(double[] arrayOfdouble_1) throws RemoteException;

   public double[][] doubleMultiArrayTest(double[][] arrayOfarrayOfdouble_1) throws RemoteException;

   public double doubleTest(double double_1) throws RemoteException;

   public float[] floatArrayTest(float[] arrayOffloat_1) throws RemoteException;

   public float[][] floatMultiArrayTest(float[][] arrayOfarrayOffloat_1) throws RemoteException;

   public float floatTest(float float_1) throws RemoteException;

   public int[] intArrayTest(int[] arrayOfint_1) throws RemoteException;

   public int[][] intMultiArrayTest(int[][] arrayOfarrayOfint_1) throws RemoteException;

   public int intTest(int int_1) throws RemoteException;

   public JavaBean[] javaBeanArrayTest(JavaBean[] arrayOfJavaBean_1) throws RemoteException;

   public JavaBean[][] javaBeanMultiArrayTest(JavaBean[][] arrayOfarrayOfJavaBean_1) throws RemoteException;

   public JavaBean javaBeanTest(JavaBean javaBean_1) throws RemoteException;

   public long[] longArrayTest(long[] arrayOflong_1) throws RemoteException;

   public long[][] longMultiArrayTest(long[][] arrayOfarrayOflong_1) throws RemoteException;

   public long longTest(long long_1) throws RemoteException;

   public void myServiceExceptionTest() throws MyServiceException, RemoteException;

   public short[] shortArrayTest(short[] arrayOfshort_1) throws RemoteException;

   public short[][] shortMultiArrayTest(short[][] arrayOfarrayOfshort_1) throws RemoteException;

   public short shortTest(short short_1) throws RemoteException;

   public String[] stringArrayTest(String[] arrayOfString_1) throws RemoteException;

   public String[][] stringMultiArrayTest(String[][] arrayOfarrayOfString_1) throws RemoteException;

   public String stringTest(String string_1) throws RemoteException;

   public ValueType[] valueTypeArrayTest(ValueType[] arrayOfValueType_1) throws RemoteException;

   public ValueType[][] valueTypeMultiArrayTest(ValueType[][] arrayOfarrayOfValueType_1) throws RemoteException;

   public ValueType valueTypeTest(ValueType valueType_1) throws RemoteException;

   public void voidTest() throws RemoteException;

   public Boolean wrapperBooleanTest(Boolean boolean_1) throws RemoteException;

   public Byte wrapperByteTest(Byte byte_1) throws RemoteException;

   public Double wrapperDoubleTest(Double double_1) throws RemoteException;

   public Float wrapperFloatTest(Float float_1) throws RemoteException;

   public Integer wrapperIntegerTest(Integer integer_1) throws RemoteException;

   public Long wrapperLongTest(Long long_1) throws RemoteException;

   public Short wrapperShortTest(Short short_1) throws RemoteException;
}
