/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2006, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxrpc.jbws637;


public class DocumentSummary {
    protected org.jboss.test.ws.jaxrpc.jbws637.Words[] misspelledWord;
    protected java.lang.String ver;
    protected java.lang.String body;
    protected int misspelledWordCount;
    
    public DocumentSummary() {
    }
    
    public DocumentSummary(org.jboss.test.ws.jaxrpc.jbws637.Words[] misspelledWord, java.lang.String ver, java.lang.String body, int misspelledWordCount) {
        this.misspelledWord = misspelledWord;
        this.ver = ver;
        this.body = body;
        this.misspelledWordCount = misspelledWordCount;
    }
    
    public org.jboss.test.ws.jaxrpc.jbws637.Words[] getMisspelledWord() {
        return misspelledWord;
    }
    
    public void setMisspelledWord(org.jboss.test.ws.jaxrpc.jbws637.Words[] misspelledWord) {
        this.misspelledWord = misspelledWord;
    }
    
    public java.lang.String getVer() {
        return ver;
    }
    
    public void setVer(java.lang.String ver) {
        this.ver = ver;
    }
    
    public java.lang.String getBody() {
        return body;
    }
    
    public void setBody(java.lang.String body) {
        this.body = body;
    }
    
    public int getMisspelledWordCount() {
        return misspelledWordCount;
    }
    
    public void setMisspelledWordCount(int misspelledWordCount) {
        this.misspelledWordCount = misspelledWordCount;
    }
}
