<?xml version="1.0" encoding="UTF-8"?>
<definitions name='TestService' targetNamespace='http://org.jboss.test.ws/jbws1190' xmlns='http://schemas.xmlsoap.org/wsdl/' xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/' xmlns:tns='http://org.jboss.test.ws/jbws1190' xmlns:xsd='http://www.w3.org/2001/XMLSchema'>
 <types/>
 <message name='TestEndpoint_testAddress'>
  <part name='String_1' type='xsd:string'/>
  <part name='String_2' type='xsd:string'/>
  <part name='String_3' type='xsd:string'/>
  <part name='String_4' type='xsd:string'/>
 </message>
 <message name='TestEndpoint_testAddressResponse'/>
 <portType name='TestEndpoint'>
  <operation name='testAddress' parameterOrder='String_1 String_2 String_3 String_4'>
   <input message='tns:TestEndpoint_testAddress'/>
   <output message='tns:TestEndpoint_testAddressResponse'/>
  </operation>
 </portType>
 <binding name='TestEndpointBinding' type='tns:TestEndpoint'>
  <soap:binding style='rpc' transport='http://schemas.xmlsoap.org/soap/http'/>
  <operation name='testAddress'>
   <soap:operation soapAction=''/>
   <input>
    <soap:body namespace='http://org.jboss.test.ws/jbws1190' use='literal'/>
   </input>
   <output>
    <soap:body namespace='http://org.jboss.test.ws/jbws1190' use='literal'/>
   </output>
  </operation>
 </binding>
 <service name='TestService'>
  <port binding='tns:TestEndpointBinding' name='TestEndpointPort'>
   <soap:address location='REPLACE_WITH_ACTUAL_URL'/>
  </port>
 </service>
</definitions>