/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2006, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
//Auto Generated by jbossws - Please do not edit!!!
package org.jboss.test.ws.jaxrpc.wsse.signup;

public class AccountSignup_signup_RequestStruct
{

   protected org.jboss.test.ws.jaxrpc.wsse.signup.AccountInfo accountInfo;

   protected float discountAmount;

   protected java.util.Date signupTime;

   public AccountSignup_signup_RequestStruct()
   {
   }

   public AccountSignup_signup_RequestStruct(org.jboss.test.ws.jaxrpc.wsse.signup.AccountInfo accountInfo, float discountAmount,
         java.util.Date signupTime)
   {
      this.accountInfo = accountInfo;
      this.discountAmount = discountAmount;
      this.signupTime = signupTime;
   }

   public org.jboss.test.ws.jaxrpc.wsse.signup.AccountInfo getAccountInfo()
   {
      return accountInfo;
   }

   public void setAccountInfo(org.jboss.test.ws.jaxrpc.wsse.signup.AccountInfo accountInfo)
   {
      this.accountInfo = accountInfo;
   }

   public float getDiscountAmount()
   {
      return discountAmount;
   }

   public void setDiscountAmount(float discountAmount)
   {
      this.discountAmount = discountAmount;
   }

   public java.util.Date getSignupTime()
   {
      return signupTime;
   }

   public void setSignupTime(java.util.Date signupTime)
   {
      this.signupTime = signupTime;
   }

}
