/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2006, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.test.ws.jaxrpc.encoded.parametermode;


public class AllStruct {
    protected java.lang.String varString;
    protected java.math.BigInteger varInteger;
    protected int varInt;
    protected long varLong;
    protected short varShort;
    protected java.math.BigDecimal varDecimal;
    protected float varFloat;
    protected double varDouble;
    protected boolean varBoolean;
    protected byte varByte;
    protected javax.xml.namespace.QName varQName;
    protected java.util.Calendar varDateTime;
    protected java.lang.String varSoapString;
    protected java.lang.Boolean varSoapBoolean;
    protected java.lang.Float varSoapFloat;
    protected java.lang.Double varSoapDouble;
    protected java.math.BigDecimal varSoapDecimal;
    protected java.lang.Integer varSoapInt;
    protected java.lang.Short varSoapShort;
    protected java.lang.Byte varSoapByte;
    protected byte[] varBase64Binary;
    protected byte[] varHexBinary;
    protected byte[] varSoapBase64;
    
    public AllStruct() {
    }
    
    public AllStruct(java.lang.String varString, java.math.BigInteger varInteger, int varInt, long varLong, short varShort, java.math.BigDecimal varDecimal, float varFloat, double varDouble, boolean varBoolean, byte varByte, javax.xml.namespace.QName varQName, java.util.Calendar varDateTime, java.lang.String varSoapString, java.lang.Boolean varSoapBoolean, java.lang.Float varSoapFloat, java.lang.Double varSoapDouble, java.math.BigDecimal varSoapDecimal, java.lang.Integer varSoapInt, java.lang.Short varSoapShort, java.lang.Byte varSoapByte, byte[] varBase64Binary, byte[] varHexBinary, byte[] varSoapBase64) {
        this.varString = varString;
        this.varInteger = varInteger;
        this.varInt = varInt;
        this.varLong = varLong;
        this.varShort = varShort;
        this.varDecimal = varDecimal;
        this.varFloat = varFloat;
        this.varDouble = varDouble;
        this.varBoolean = varBoolean;
        this.varByte = varByte;
        this.varQName = varQName;
        this.varDateTime = varDateTime;
        this.varSoapString = varSoapString;
        this.varSoapBoolean = varSoapBoolean;
        this.varSoapFloat = varSoapFloat;
        this.varSoapDouble = varSoapDouble;
        this.varSoapDecimal = varSoapDecimal;
        this.varSoapInt = varSoapInt;
        this.varSoapShort = varSoapShort;
        this.varSoapByte = varSoapByte;
        this.varBase64Binary = varBase64Binary;
        this.varHexBinary = varHexBinary;
        this.varSoapBase64 = varSoapBase64;
    }
    
    public java.lang.String getVarString() {
        return varString;
    }
    
    public void setVarString(java.lang.String varString) {
        this.varString = varString;
    }
    
    public java.math.BigInteger getVarInteger() {
        return varInteger;
    }
    
    public void setVarInteger(java.math.BigInteger varInteger) {
        this.varInteger = varInteger;
    }
    
    public int getVarInt() {
        return varInt;
    }
    
    public void setVarInt(int varInt) {
        this.varInt = varInt;
    }
    
    public long getVarLong() {
        return varLong;
    }
    
    public void setVarLong(long varLong) {
        this.varLong = varLong;
    }
    
    public short getVarShort() {
        return varShort;
    }
    
    public void setVarShort(short varShort) {
        this.varShort = varShort;
    }
    
    public java.math.BigDecimal getVarDecimal() {
        return varDecimal;
    }
    
    public void setVarDecimal(java.math.BigDecimal varDecimal) {
        this.varDecimal = varDecimal;
    }
    
    public float getVarFloat() {
        return varFloat;
    }
    
    public void setVarFloat(float varFloat) {
        this.varFloat = varFloat;
    }
    
    public double getVarDouble() {
        return varDouble;
    }
    
    public void setVarDouble(double varDouble) {
        this.varDouble = varDouble;
    }
    
    public boolean isVarBoolean() {
        return varBoolean;
    }
    
    public void setVarBoolean(boolean varBoolean) {
        this.varBoolean = varBoolean;
    }
    
    public byte getVarByte() {
        return varByte;
    }
    
    public void setVarByte(byte varByte) {
        this.varByte = varByte;
    }
    
    public javax.xml.namespace.QName getVarQName() {
        return varQName;
    }
    
    public void setVarQName(javax.xml.namespace.QName varQName) {
        this.varQName = varQName;
    }
    
    public java.util.Calendar getVarDateTime() {
        return varDateTime;
    }
    
    public void setVarDateTime(java.util.Calendar varDateTime) {
        this.varDateTime = varDateTime;
    }
    
    public java.lang.String getVarSoapString() {
        return varSoapString;
    }
    
    public void setVarSoapString(java.lang.String varSoapString) {
        this.varSoapString = varSoapString;
    }
    
    public java.lang.Boolean getVarSoapBoolean() {
        return varSoapBoolean;
    }
    
    public void setVarSoapBoolean(java.lang.Boolean varSoapBoolean) {
        this.varSoapBoolean = varSoapBoolean;
    }
    
    public java.lang.Float getVarSoapFloat() {
        return varSoapFloat;
    }
    
    public void setVarSoapFloat(java.lang.Float varSoapFloat) {
        this.varSoapFloat = varSoapFloat;
    }
    
    public java.lang.Double getVarSoapDouble() {
        return varSoapDouble;
    }
    
    public void setVarSoapDouble(java.lang.Double varSoapDouble) {
        this.varSoapDouble = varSoapDouble;
    }
    
    public java.math.BigDecimal getVarSoapDecimal() {
        return varSoapDecimal;
    }
    
    public void setVarSoapDecimal(java.math.BigDecimal varSoapDecimal) {
        this.varSoapDecimal = varSoapDecimal;
    }
    
    public java.lang.Integer getVarSoapInt() {
        return varSoapInt;
    }
    
    public void setVarSoapInt(java.lang.Integer varSoapInt) {
        this.varSoapInt = varSoapInt;
    }
    
    public java.lang.Short getVarSoapShort() {
        return varSoapShort;
    }
    
    public void setVarSoapShort(java.lang.Short varSoapShort) {
        this.varSoapShort = varSoapShort;
    }
    
    public java.lang.Byte getVarSoapByte() {
        return varSoapByte;
    }
    
    public void setVarSoapByte(java.lang.Byte varSoapByte) {
        this.varSoapByte = varSoapByte;
    }
    
    public byte[] getVarBase64Binary() {
        return varBase64Binary;
    }
    
    public void setVarBase64Binary(byte[] varBase64Binary) {
        this.varBase64Binary = varBase64Binary;
    }
    
    public byte[] getVarHexBinary() {
        return varHexBinary;
    }
    
    public void setVarHexBinary(byte[] varHexBinary) {
        this.varHexBinary = varHexBinary;
    }
    
    public byte[] getVarSoapBase64() {
        return varSoapBase64;
    }
    
    public void setVarSoapBase64(byte[] varSoapBase64) {
        this.varSoapBase64 = varSoapBase64;
    }
}
