/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2006, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxrpc.jbws775;


public class TextTranslator_quoteTranslation_RequestStruct {
    protected java.lang.String clientName;
    protected java.lang.String text;
    protected java.lang.String sourceLanguage;
    protected java.lang.String targetLanguage;
    
    public TextTranslator_quoteTranslation_RequestStruct() {
    }
    
    public TextTranslator_quoteTranslation_RequestStruct(java.lang.String clientName, java.lang.String text, java.lang.String sourceLanguage, java.lang.String targetLanguage) {
        this.clientName = clientName;
        this.text = text;
        this.sourceLanguage = sourceLanguage;
        this.targetLanguage = targetLanguage;
    }
    
    public java.lang.String getClientName() {
        return clientName;
    }
    
    public void setClientName(java.lang.String clientName) {
        this.clientName = clientName;
    }
    
    public java.lang.String getText() {
        return text;
    }
    
    public void setText(java.lang.String text) {
        this.text = text;
    }
    
    public java.lang.String getSourceLanguage() {
        return sourceLanguage;
    }
    
    public void setSourceLanguage(java.lang.String sourceLanguage) {
        this.sourceLanguage = sourceLanguage;
    }
    
    public java.lang.String getTargetLanguage() {
        return targetLanguage;
    }
    
    public void setTargetLanguage(java.lang.String targetLanguage) {
        this.targetLanguage = targetLanguage;
    }
}
