/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2006, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxrpc.jbws663;


public class MessageStatus {
    protected int statusCode;
    protected java.lang.String statusText;
    protected java.lang.String statusExtra;
    
    public MessageStatus() {
    }
    
    public MessageStatus(int statusCode, java.lang.String statusText, java.lang.String statusExtra) {
        this.statusCode = statusCode;
        this.statusText = statusText;
        this.statusExtra = statusExtra;
    }
    
    public int getStatusCode() {
        return statusCode;
    }
    
    public void setStatusCode(int statusCode) {
        this.statusCode = statusCode;
    }
    
    public java.lang.String getStatusText() {
        return statusText;
    }
    
    public void setStatusText(java.lang.String statusText) {
        this.statusText = statusText;
    }
    
    public java.lang.String getStatusExtra() {
        return statusExtra;
    }
    
    public void setStatusExtra(java.lang.String statusExtra) {
        this.statusExtra = statusExtra;
    }
}
