/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2006, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxrpc.jbws663;


public class SendMessagesBulk {
    protected org.jboss.test.ws.jaxrpc.jbws663.ArrayOfString toNumbers;
    protected java.lang.String fromNumber;
    protected java.lang.String fromName;
    protected java.lang.String messageText;
    
    public SendMessagesBulk() {
    }
    
    public SendMessagesBulk(org.jboss.test.ws.jaxrpc.jbws663.ArrayOfString toNumbers, java.lang.String fromNumber, java.lang.String fromName, java.lang.String messageText) {
        this.toNumbers = toNumbers;
        this.fromNumber = fromNumber;
        this.fromName = fromName;
        this.messageText = messageText;
    }
    
    public org.jboss.test.ws.jaxrpc.jbws663.ArrayOfString getToNumbers() {
        return toNumbers;
    }
    
    public void setToNumbers(org.jboss.test.ws.jaxrpc.jbws663.ArrayOfString toNumbers) {
        this.toNumbers = toNumbers;
    }
    
    public java.lang.String getFromNumber() {
        return fromNumber;
    }
    
    public void setFromNumber(java.lang.String fromNumber) {
        this.fromNumber = fromNumber;
    }
    
    public java.lang.String getFromName() {
        return fromName;
    }
    
    public void setFromName(java.lang.String fromName) {
        this.fromName = fromName;
    }
    
    public java.lang.String getMessageText() {
        return messageText;
    }
    
    public void setMessageText(java.lang.String messageText) {
        this.messageText = messageText;
    }
}
