/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2006, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.wsdlimportwithusertypes;


public class Composite {
    protected org.jboss.test.webservice.wsdlimportwithusertypes.Composite composite;
    protected java.util.Calendar dateTime;
    protected java.math.BigInteger integer;
    protected javax.xml.namespace.QName qname;
    protected java.lang.String string;
    
    public Composite() {
    }
    
    public Composite(org.jboss.test.webservice.wsdlimportwithusertypes.Composite composite, java.util.Calendar dateTime, java.math.BigInteger integer, javax.xml.namespace.QName qname, java.lang.String string) {
        this.composite = composite;
        this.dateTime = dateTime;
        this.integer = integer;
        this.qname = qname;
        this.string = string;
    }
    
    public org.jboss.test.webservice.wsdlimportwithusertypes.Composite getComposite() {
        return composite;
    }
    
    public void setComposite(org.jboss.test.webservice.wsdlimportwithusertypes.Composite composite) {
        this.composite = composite;
    }
    
    public java.util.Calendar getDateTime() {
        return dateTime;
    }
    
    public void setDateTime(java.util.Calendar dateTime) {
        this.dateTime = dateTime;
    }
    
    public java.math.BigInteger getInteger() {
        return integer;
    }
    
    public void setInteger(java.math.BigInteger integer) {
        this.integer = integer;
    }
    
    public javax.xml.namespace.QName getQname() {
        return qname;
    }
    
    public void setQname(javax.xml.namespace.QName qname) {
        this.qname = qname;
    }
    
    public java.lang.String getString() {
        return string;
    }
    
    public void setString(java.lang.String string) {
        this.string = string;
    }
}
