/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2006, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
package org.jboss.test.ws.tools.jbws_204.wscompile.anontypes;


public class ItemsItem {
    protected java.lang.String productName;
    protected java.math.BigInteger quantity;
    protected java.math.BigDecimal USPrice;
    protected java.util.Calendar shipDate;

    public ItemsItem() {
    }

    public ItemsItem(java.lang.String productName, java.math.BigInteger quantity, java.math.BigDecimal USPrice, java.util.Calendar shipDate) {
        this.productName = productName;
        this.quantity = quantity;
        this.USPrice = USPrice;
        this.shipDate = shipDate;
        }

    public java.lang.String getProductName() {
        return productName;
    }

    public void setProductName(java.lang.String productName) {
        this.productName = productName;
    }

    public java.math.BigInteger getQuantity() {
        return quantity;
    }

    public void setQuantity(java.math.BigInteger quantity) {
        this.quantity = quantity;
    }

    public java.math.BigDecimal getUSPrice() {
        return USPrice;
    }

    public void setUSPrice(java.math.BigDecimal USPrice) {
        this.USPrice = USPrice;
    }

    public java.util.Calendar getShipDate() {
        return shipDate;
    }

    public void setShipDate(java.util.Calendar shipDate) {
        this.shipDate = shipDate;
    }
}
