/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2006, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package org.jboss.test.ws.jaxrpc.jbws751;


public class TransactionHistoryRs {
    protected java.lang.String sessionId;
    protected java.lang.Integer recordPointer;
    protected org.jboss.test.ws.jaxrpc.jbws751.ShareTransactionHistory_Type shareHistory;
    protected org.jboss.test.ws.jaxrpc.jbws751.LoanTransactionHistory_Type loanHistory;
    
    public TransactionHistoryRs() {
    }
    
    public TransactionHistoryRs(java.lang.String sessionId, java.lang.Integer recordPointer, org.jboss.test.ws.jaxrpc.jbws751.ShareTransactionHistory_Type shareHistory, org.jboss.test.ws.jaxrpc.jbws751.LoanTransactionHistory_Type loanHistory) {
        this.sessionId = sessionId;
        this.recordPointer = recordPointer;
        this.shareHistory = shareHistory;
        this.loanHistory = loanHistory;
    }
    
    public java.lang.String getSessionId() {
        return sessionId;
    }
    
    public void setSessionId(java.lang.String sessionId) {
        this.sessionId = sessionId;
    }
    
    public java.lang.Integer getRecordPointer() {
        return recordPointer;
    }
    
    public void setRecordPointer(java.lang.Integer recordPointer) {
        this.recordPointer = recordPointer;
    }
    
    public org.jboss.test.ws.jaxrpc.jbws751.ShareTransactionHistory_Type getShareHistory() {
        return shareHistory;
    }
    
    public void setShareHistory(org.jboss.test.ws.jaxrpc.jbws751.ShareTransactionHistory_Type shareHistory) {
        this.shareHistory = shareHistory;
    }
    
    public org.jboss.test.ws.jaxrpc.jbws751.LoanTransactionHistory_Type getLoanHistory() {
        return loanHistory;
    }
    
    public void setLoanHistory(org.jboss.test.ws.jaxrpc.jbws751.LoanTransactionHistory_Type loanHistory) {
        this.loanHistory = loanHistory;
    }
}
