/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2006, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
//Auto Generated by jbossws - Please do not edit!!!
package org.jboss.test.ws.jaxrpc.jbws381;

public class WeatherForecasts
{

   protected float latitude;

   protected float longitude;

   protected float allocationFactor;

   protected java.lang.String fipsCode;

   protected java.lang.String placeName;

   protected java.lang.String stateCode;

   protected java.lang.String status;

   protected org.jboss.test.ws.jaxrpc.jbws381.WeatherData[] details;

   public WeatherForecasts()
   {
   }

   public WeatherForecasts(float latitude, float longitude, float allocationFactor, java.lang.String fipsCode,
         java.lang.String placeName, java.lang.String stateCode, java.lang.String status,
         org.jboss.test.ws.jaxrpc.jbws381.WeatherData[] details)
   {
      this.latitude = latitude;
      this.longitude = longitude;
      this.allocationFactor = allocationFactor;
      this.fipsCode = fipsCode;
      this.placeName = placeName;
      this.stateCode = stateCode;
      this.status = status;
      this.details = details;
   }

   public float getLatitude()
   {
      return latitude;
   }

   public void setLatitude(float latitude)
   {
      this.latitude = latitude;
   }

   public float getLongitude()
   {
      return longitude;
   }

   public void setLongitude(float longitude)
   {
      this.longitude = longitude;
   }

   public float getAllocationFactor()
   {
      return allocationFactor;
   }

   public void setAllocationFactor(float allocationFactor)
   {
      this.allocationFactor = allocationFactor;
   }

   public java.lang.String getFipsCode()
   {
      return fipsCode;
   }

   public void setFipsCode(java.lang.String fipsCode)
   {
      this.fipsCode = fipsCode;
   }

   public java.lang.String getPlaceName()
   {
      return placeName;
   }

   public void setPlaceName(java.lang.String placeName)
   {
      this.placeName = placeName;
   }

   public java.lang.String getStateCode()
   {
      return stateCode;
   }

   public void setStateCode(java.lang.String stateCode)
   {
      this.stateCode = stateCode;
   }

   public java.lang.String getStatus()
   {
      return status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public org.jboss.test.ws.jaxrpc.jbws381.WeatherData[] getDetails()
   {
      return details;
   }

   public void setDetails(org.jboss.test.ws.jaxrpc.jbws381.WeatherData[] details)
   {
      this.details = details;
   }

}
