/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2006, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
//Auto Generated by jbossws - Please do not edit!!!
package org.jboss.test.ws.jaxrpc.jbws381;

public class WeatherData
{

   protected java.lang.String day;

   protected java.lang.String weatherImage;

   protected java.lang.String maxTemperatureF;

   protected java.lang.String minTemperatureF;

   protected java.lang.String maxTemperatureC;

   protected java.lang.String minTemperatureC;

   public WeatherData()
   {
   }

   public WeatherData(java.lang.String day, java.lang.String weatherImage, java.lang.String maxTemperatureF,
         java.lang.String minTemperatureF, java.lang.String maxTemperatureC, java.lang.String minTemperatureC)
   {
      this.day = day;
      this.weatherImage = weatherImage;
      this.maxTemperatureF = maxTemperatureF;
      this.minTemperatureF = minTemperatureF;
      this.maxTemperatureC = maxTemperatureC;
      this.minTemperatureC = minTemperatureC;
   }

   public java.lang.String getDay()
   {
      return day;
   }

   public void setDay(java.lang.String day)
   {
      this.day = day;
   }

   public java.lang.String getWeatherImage()
   {
      return weatherImage;
   }

   public void setWeatherImage(java.lang.String weatherImage)
   {
      this.weatherImage = weatherImage;
   }

   public java.lang.String getMaxTemperatureF()
   {
      return maxTemperatureF;
   }

   public void setMaxTemperatureF(java.lang.String maxTemperatureF)
   {
      this.maxTemperatureF = maxTemperatureF;
   }

   public java.lang.String getMinTemperatureF()
   {
      return minTemperatureF;
   }

   public void setMinTemperatureF(java.lang.String minTemperatureF)
   {
      this.minTemperatureF = minTemperatureF;
   }

   public java.lang.String getMaxTemperatureC()
   {
      return maxTemperatureC;
   }

   public void setMaxTemperatureC(java.lang.String maxTemperatureC)
   {
      this.maxTemperatureC = maxTemperatureC;
   }

   public java.lang.String getMinTemperatureC()
   {
      return minTemperatureC;
   }

   public void setMinTemperatureC(java.lang.String minTemperatureC)
   {
      this.minTemperatureC = minTemperatureC;
   }

}
